ob_kul = [
    "Podkramarska 5, 80-834 Gdańsk",
    "Ołowianka 9-13, 80-751 Gdańsk",
    " Ołowianka 11, 80-751 Gdańsk",
    "Gradowa 3, 80-802 Gdańsk",
    "Gradowa 6, 80-802 Gdańsk",
    "Kołobrzeska 41c, 80-391 Gdańsk",
    "Grunwaldzka 195/197, 80-266 Gdańsk",
    "Pisza 1, 80-680 Gdańsk",
    "Zwycięstwa 14, 80-219 Gdańsk",
    "Toruńska 1, 80-822 Gdańsk",
    "Długi Targ 24, 80-828 Gdańsk",
    "Ołowianka 1, 80-751 Gdańsk",
    "pl. Solidarności 1, 80-863 Gdańsk",
    "pl. Władysława Bartoszewskiego 1",
    "Szeroka 67/68, 80-835 Gdańsk",
    "Tokarska 21/25, 80-888 Gdańsk",
    "Długi Targ 43/44, 80-831 Gdańsk",
    "Długa 46, 80-831 Gdańsk",
    "Cystersów 18, 80-330 Gdańsk",
    "Cystersów 19, 80-330 Gdańsk",
    "Długi Targ 24, 80-828 Gdańsk",
    "Mariacka 25/26, 80-833 Gdańsk",
]

nazwa_ob_kult = [
    "Bazylika Mariacka, pw. Wniebowzięcia NMP",
    "Centralne Muzeum Morskie",
    "Centralne Muzeum Morskie - Sołdek",
    "Centrum Hewelianum (PKFM 'Twierdza Gdańsk', Grodzisko)",
    'Park Kulturowy Fortyfikacji Miejskich "Twierdza Gdańsk" (Grodzisko)',
    'Kino Helios w "Alfie Centrum"',
    "klub Żak",
    "Kościół pw. Matki Boskiej Saletyńskiej",
    "Multikino",
    "Muzeum Narodowe w Gdańsku-Oddział Sztuki Dawnej",
    "Muzeum Narodowe w Gdańsku - Oddział Zielona Brama",
    "Polska Filharmonia Bałtycka im. Fryderyka Chopina w Gdańsku",
    "Europejskie Centrum Solidarności",
    "Muzeum II wojny światowej",
    "Żuraw",
    "Ośrodek Kultury Morskiej",
    "Dwór Artusa",
    "Ratuszcz Główny Miasta",
    "Muzeum Narodowe w Gdańsku / Oddział Sztuki Nowoczesnej.",
    "Muzeum Narodowe w Gdańsku / Oddział Etnografii",
    "Muzeum Narodowe w Gdańsku / Gdańska Galeria Fotografi",
    "Muzeum Archelogiczne w Gdańsku",

]

dostepnosc = [
    "Potrzeba otwarcia<b> dwóch skrzydeł drzwi</b>Należy skierować<b> do obsługi </b> aby postawili podjazd ",
    "Wejście bez schodów ze strony parkingu Winda obsługuje wszystkie trzy poziomy. Toalety dostosowane do potrzeb osób z niepełnosprawnością .",
    "Statek nieprzystosowany do zwiedzania dla osób z niepełnosprawnością ruchową oraz osób niedowidzących lub niewidomych z uwagi na specyfikę obiektu.",
    "Od strony parkingu brak schodków i tym wejściem <b>należy wchodzić</b>. Winda obsługuje wszystkie piętra oraz są toalety dostosowane do osób z niepełnosprawnością. ",
    "Wjazd wózkiem podjazd od ul. 3 Maja lub ul. Dąbrowskiego i ul. Gradową (można samochodem); <b> zjazdy i podjazdy wymagają pomocy 2.osoby<b>,  szer. 90cm drzwi schronów",
    "Wjazd wózkiem podjazd od ul. 3 Maja lub ul. Dąbrowskiego i ul. Gradową (można samochodem). 90 cm to szer. drzwi schronów  gdzie są ekspozycje. ",
    "Kino znajduje się w centrum handlowym na poziomie +2. Wydzielone są miejsca na wózki. Toalety są dostosowane do osób z niepełnosprawnością znajdują się zaraz obok sal. Winda obsługuje wszystkie piętra. ",
    "Wszystkie osoby z niepełnosprawnością bez problemu dostaną się do środka. Toaleta jest na parterze oraz na piętrze.",
    "Furtka ogrodzenia kościelnego szer. 90 cm; toalety w przykościelnym Klubie Parafialnym lub Domu Pielgrzyma",
    "Wejście do sali kinowej szer. 120 cm; wjazd samochodem na parking od ul. Towarowej (za Operą Bałtycką); drzwi 2-skrzydłowe, jeżeli otworzyć oba skrzydła, to 180 cm.",
    " Winda na wszystkie piętra (ekspozycje); przyciski w windzie w brajlu; obniżona lada z kasą; okresowo multimedia dźwiękowe; 1schodek do budynku i schody w dół (poziom -1) do dostosowanej toalety, ale tu pomoże personel i ochrona",
    "Zestawy dla niedosłyszących-słuchawki w kasie, szer. drzwi do kasy 90 cm. Winda na I piętro, przyciski w windzie w brajlu. Płaskie wejście do Sali Kameralnej, podjazd do Sali Koncertowej i zjazdy z foyer do Sali i miejsca na wózek. Toaleta na parterze.",
    "Przed wejściem są podjazdy, 2 windy jeżdżące po wszystkich piętrach, schody ruchome i toalety dostosowane do osób z niepełnosprawnością.",
    "Przed wejściem są podjazdy, 2 windy jeżdżące po wszystkich piętrach, schody ruchome i toalety dostosowane do osób z niepełnosprawnością.",
    "Budynek nieprzystosowany do zwiedzania dla osób z ograniczeniami ruchowymi oraz osób niedowidzących lub niewidomych z uwagi na architekturę obiektu zabytkowego.",
    "Wejścia są płaskie i są to automatyczne otwierające drzwi. Winda obsługuje wszystkie piętra.",
    "Posiada zaplecze umożliwiające turystom na wózkach inwalidzkich swobodne poruszanie się. Wejście znajduje się na tyłach Dworu Artusa, od ulicy Chlebnickiej.",
    "Zwiedzanie Ratusza Głównego Miasta możliwe jest dzięki windzie, do której wejście znajduje się na tyłach budynku, tj. od ulicy Piwnej. Winda dowozi na wszystkie poziomy sal wystawowych oprócz wieży widokowej Ratusza. W obiekcie znajdują się także toalety dostosowane do potrzeb osób niepełnosprawnych ruchowo oraz rampy i podjazdy.",
    "Wejście do budynku Pałacu Opatów – jeden wysoki stopień i drzwi otwierane do wewnątrz. Bezpośrednio za drzwiami wejściowymi znajduje się kasa biletowa, a w sąsiadującym holu – szatnia obsługiwana przez pracowników służby ochrony MNG. Brak indywidualnych zamykanych szafek. Brak toalety przystosowanej dla osób niepełnosprawnych. Brak toalety z przewijakiem.",
    "Wejście do budynku Oddziału Etnografii znajduje się tuż po lewej stronie bezpośrednio po wejściu przez bramę do Parku Oliwskiego od Katedry Oliwskiej. Do drzwi wejściowych prowadzi niedawno wyremontowany płaski i równy chodnik. Wejście do budynku – bez bariery jakiegokolwiek podwyższenia.",
    "Bezpośrednio za drzwiami wejściowymi znajduje się kasa biletowa i szatnia obsługiwana przez pracowników służby ochrony MNG. Brak indywidualnych zamykanych szafek. Brak toalety przystosowanej dla osób niepełnosprawnych. Osoby ze specjalnymi potrzebami proszone są o ich zgłoszenie przy zakupie biletu. Dostęp do sal wystawienniczych Gdańskiej Galerii Fotografii za pomocą windy, jednak na II piętrze trzeba pokonać barierę kilku stopni schodów prowadzących na III piętro.",
    "Z powodu zabytkowej struktury jest problem dostania do środka."
]

icon = [
    "circle",
    "ship",
    "ship",
    "globe",
    "globe",
    "film",
    "film",
    "circle",
    "film",
    "image",
    "image",
    "music",
    "history",
    "history",
    "ship",
    "ship",
    "history",
    "history",
    "history",
    "history",
    "history",
    "image",
    "history",
]
# print(len(icon))
# print(len(ob_kul))
kolory = [
    "blue",
    'lightblue',
    'darkblue',]
